// gifts-data.js - base de dados dos presentes com códigos mascarados
window.GIFTS_DATABASE = {
  eletros: [
    { id: "EL-1001", title: "Air fryer", desc: "Item da lista de presentes.", price: "110v" },
    { id: "EL-1002", title: "Liquidificador", desc: "Item da lista de presentes.", price: "110v" },
    { id: "EL-1003", title: "Batedeira", desc: "Item da lista de presentes.", price: "110v" },
    { id: "EL-1004", title: "Cafeteira elétrica", desc: "Item da lista de presentes.", price: "110v" },
    { id: "EL-1005", title: "Torradeira", desc: "Item da lista de presentes.", price: "110v" },
    { id: "EL-1006", title: "Sanduicheira", desc: "Item da lista de presentes.", price: "110v" },
    { id: "EL-1007", title: "Chaleira elétrica", desc: "Item da lista de presentes.", price: "110v" },
    { id: "EL-1008", title: "Aspirador de pó", desc: "Item da lista de presentes.", price: "110v" },
    { id: "EL-1009", title: "Ventilador vertical", desc: "Item da lista de presentes.", price: "110v" },
    { id: "EL-1010", title: "Televisão", desc: "Item da lista de presentes.", price: "110v" },
    { id: "EL-1011", title: "Alexa", desc: "Item da lista de presentes.", price: "" },
    { id: "EL-1012", title: "Ar condicionado (12.000 BTU)", desc: "Item da lista de presentes.", price: "220v" },
    { id: "EL-1013", title: "Ferro de passar", desc: "Item da lista de presentes.", price: "110v" },
    { id: "EL-1014", title: "Panela de pressão elétrica", desc: "Item da lista de presentes.", price: "110v" },
    { id: "EL-1015", title: "Mixer", desc: "Item da lista de presentes.", price: "110v" },
    { id: "EL-1016", title: "Robô aspirador", desc: "Item da lista de presentes.", price: "110v" },
    { id: "EL-1017", title: "Secador de cabelo", desc: "Item da lista de presentes.", price: "110v" },
    { id: "EL-1018", title: "Lava-louças", desc: "Item da lista de presentes.", price: "110v" },
  ],
  cozinha: [
    { id: "CZ-2001", title: "Jogo de pratos", desc: "Item da lista de presentes.", price: "-" },
    { id: "CZ-2002", title: "Jogo de copos", desc: "Item da lista de presentes.", price: "-" },
    { id: "CZ-2003", title: "Jogo de taças", desc: "Item da lista de presentes.", price: "-" },
    { id: "CZ-2004", title: "Jogo de xícaras", desc: "Item da lista de presentes.", price: "-" },
    { id: "CZ-2005", title: "Canecas", desc: "Item da lista de presentes.", price: "-" },
    { id: "CZ-2006", title: "Faqueiro", desc: "Item da lista de presentes.", price: "-" },
    { id: "CZ-2007", title: "Talheres para churrasco", desc: "Item da lista de presentes.", price: "-" },
    { id: "CZ-2008", title: "Tábua de churrasco", desc: "Item da lista de presentes.", price: "-" },
    { id: "CZ-2009", title: "Forma para bolo", desc: "Item da lista de presentes.", price: "-" },
    { id: "CZ-2010", title: "Assadeira", desc: "Item da lista de presentes.", price: "-" },
    { id: "CZ-2011", title: "Travessa de vidro", desc: "Item da lista de presentes.", price: "-" },
    { id: "CZ-2012", title: "Jarra de vidro", desc: "Item da lista de presentes.", price: "-" },
    { id: "CZ-2013", title: "Jogo de panelas", desc: "Item da lista de presentes.", price: "-" },
    { id: "CZ-2014", title: "Frigideira antiaderente", desc: "Item da lista de presentes.", price: "-" },
    { id: "CZ-2015", title: "Panela de pressão elétrica", desc: "Item da lista de presentes.", price: "-" },
    { id: "CZ-2016", title: "Potes herméticos", desc: "Item da lista de presentes.", price: "-" },
    { id: "CZ-2017", title: "Panos de prato", desc: "Item da lista de presentes.", price: "-" },
    { id: "CZ-2018", title: "Espetos para churrasco", desc: "Item da lista de presentes.", price: "-" },
  ],
  cama: [
    { id: "CM-3001", title: "Edredom casal", desc: "Item da lista de presentes.", price: "-" },
    { id: "CM-3002", title: "Jogo de cama casal", desc: "Item da lista de presentes.", price: "-" },
    { id: "CM-3003", title: "Toalhas de banho", desc: "Item da lista de presentes.", price: "-" },
    { id: "CM-3004", title: "Toalhas de rosto", desc: "Item da lista de presentes.", price: "-" },
    { id: "CM-3005", title: "Roupão", desc: "Item da lista de presentes.", price: "-" },
    { id: "CM-3006", title: "Travesseiros", desc: "Item da lista de presentes.", price: "-" },
  ],
  decor: [
    { id: "DC-4001", title: "Jogo de Ferramentas", desc: "Item da lista de presentes.", price: "-" },
  ],
};
